#pragma once
#include "libevsig/signals.h"
#include <errno.h>

#ifdef __cplusplus
extern "C" {
#endif

// Returns NULL if the errno can't be converted
const char* sig_from_errno(int errno_in);

// Produces prefixed string from errno.
//
// prefix must be less than 256 chars
//
// The result is stored in a thread-local variable,
// so usage in functions like printf may not work
// as you expect. Use one result at a time.

const char* str_from_errno(const char* prefix, int errno_in);

SIG_DECLTYPE(SIGNAL_E2BIG);
SIG_DECLTYPE(SIGNAL_EACCES);
SIG_DECLTYPE(SIGNAL_EADDRINUSE);
SIG_DECLTYPE(SIGNAL_EADDRNOTAVAIL);
SIG_DECLTYPE(SIGNAL_EADV);
SIG_DECLTYPE(SIGNAL_EAFNOSUPPORT);
SIG_DECLTYPE(SIGNAL_EAGAIN);
SIG_DECLTYPE(SIGNAL_EALREADY);
SIG_DECLTYPE(SIGNAL_EBADE);
SIG_DECLTYPE(SIGNAL_EBADF);
SIG_DECLTYPE(SIGNAL_EBADFD);
SIG_DECLTYPE(SIGNAL_EBADMSG);
SIG_DECLTYPE(SIGNAL_EBADR);
SIG_DECLTYPE(SIGNAL_EBADRQC);
SIG_DECLTYPE(SIGNAL_EBADSLT);
SIG_DECLTYPE(SIGNAL_EBFONT);
SIG_DECLTYPE(SIGNAL_EBUSY);
SIG_DECLTYPE(SIGNAL_ECANCELED);
SIG_DECLTYPE(SIGNAL_ECHILD);
SIG_DECLTYPE(SIGNAL_ECHRNG);
SIG_DECLTYPE(SIGNAL_ECOMM);
SIG_DECLTYPE(SIGNAL_ECONNABORTED);
SIG_DECLTYPE(SIGNAL_ECONNREFUSED);
SIG_DECLTYPE(SIGNAL_ECONNRESET);
SIG_DECLTYPE(SIGNAL_EDEADLOCK);
SIG_DECLTYPE(SIGNAL_EDESTADDRREQ);
SIG_DECLTYPE(SIGNAL_EDOM);
SIG_DECLTYPE(SIGNAL_EDOTDOT);
SIG_DECLTYPE(SIGNAL_EDQUOT);
SIG_DECLTYPE(SIGNAL_EEXIST);
SIG_DECLTYPE(SIGNAL_EFAULT);
SIG_DECLTYPE(SIGNAL_EFBIG);
SIG_DECLTYPE(SIGNAL_EHOSTDOWN);
SIG_DECLTYPE(SIGNAL_EHOSTUNREACH);
SIG_DECLTYPE(SIGNAL_EHWPOISON);
SIG_DECLTYPE(SIGNAL_EIDRM);
SIG_DECLTYPE(SIGNAL_EILSEQ);
SIG_DECLTYPE(SIGNAL_EINPROGRESS);
SIG_DECLTYPE(SIGNAL_EINTR);
SIG_DECLTYPE(SIGNAL_EINVAL);
SIG_DECLTYPE(SIGNAL_EIO);
SIG_DECLTYPE(SIGNAL_EISCONN);
SIG_DECLTYPE(SIGNAL_EISDIR);
SIG_DECLTYPE(SIGNAL_EISNAM);
SIG_DECLTYPE(SIGNAL_EKEYEXPIRED);
SIG_DECLTYPE(SIGNAL_EKEYREJECTED);
SIG_DECLTYPE(SIGNAL_EKEYREVOKED);
SIG_DECLTYPE(SIGNAL_EL2HLT);
SIG_DECLTYPE(SIGNAL_EL2NSYNC);
SIG_DECLTYPE(SIGNAL_EL3HLT);
SIG_DECLTYPE(SIGNAL_EL3RST);
SIG_DECLTYPE(SIGNAL_ELIBACC);
SIG_DECLTYPE(SIGNAL_ELIBBAD);
SIG_DECLTYPE(SIGNAL_ELIBEXEC);
SIG_DECLTYPE(SIGNAL_ELIBMAX);
SIG_DECLTYPE(SIGNAL_ELIBSCN);
SIG_DECLTYPE(SIGNAL_ELNRNG);
SIG_DECLTYPE(SIGNAL_ELOOP);
SIG_DECLTYPE(SIGNAL_EMEDIUMTYPE);
SIG_DECLTYPE(SIGNAL_EMFILE);
SIG_DECLTYPE(SIGNAL_EMLINK);
SIG_DECLTYPE(SIGNAL_EMSGSIZE);
SIG_DECLTYPE(SIGNAL_EMULTIHOP);
SIG_DECLTYPE(SIGNAL_ENAMETOOLONG);
SIG_DECLTYPE(SIGNAL_ENAVAIL);
SIG_DECLTYPE(SIGNAL_ENETDOWN);
SIG_DECLTYPE(SIGNAL_ENETRESET);
SIG_DECLTYPE(SIGNAL_ENETUNREACH);
SIG_DECLTYPE(SIGNAL_ENFILE);
SIG_DECLTYPE(SIGNAL_ENOANO);
SIG_DECLTYPE(SIGNAL_ENOBUFS);
SIG_DECLTYPE(SIGNAL_ENOCSI);
SIG_DECLTYPE(SIGNAL_ENODATA);
SIG_DECLTYPE(SIGNAL_ENODEV);
SIG_DECLTYPE(SIGNAL_ENOENT);
SIG_DECLTYPE(SIGNAL_ENOEXEC);
SIG_DECLTYPE(SIGNAL_ENOKEY);
SIG_DECLTYPE(SIGNAL_ENOLCK);
SIG_DECLTYPE(SIGNAL_ENOLINK);
SIG_DECLTYPE(SIGNAL_ENOMEDIUM);
SIG_DECLTYPE(SIGNAL_ENOMEM);
SIG_DECLTYPE(SIGNAL_ENOMSG);
SIG_DECLTYPE(SIGNAL_ENONET);
SIG_DECLTYPE(SIGNAL_ENOPKG);
SIG_DECLTYPE(SIGNAL_ENOPROTOOPT);
SIG_DECLTYPE(SIGNAL_ENOSPC);
SIG_DECLTYPE(SIGNAL_ENOSR);
SIG_DECLTYPE(SIGNAL_ENOSTR);
SIG_DECLTYPE(SIGNAL_ENOSYS);
SIG_DECLTYPE(SIGNAL_ENOTBLK);
SIG_DECLTYPE(SIGNAL_ENOTCONN);
SIG_DECLTYPE(SIGNAL_ENOTDIR);
SIG_DECLTYPE(SIGNAL_ENOTEMPTY);
SIG_DECLTYPE(SIGNAL_ENOTNAM);
SIG_DECLTYPE(SIGNAL_ENOTRECOVERABLE);
SIG_DECLTYPE(SIGNAL_ENOTSOCK);
SIG_DECLTYPE(SIGNAL_ENOTTY);
SIG_DECLTYPE(SIGNAL_ENOTUNIQ);
SIG_DECLTYPE(SIGNAL_ENXIO);
SIG_DECLTYPE(SIGNAL_EOF);
SIG_DECLTYPE(SIGNAL_EOPNOTSUPP);
SIG_DECLTYPE(SIGNAL_EOVERFLOW);
SIG_DECLTYPE(SIGNAL_EOWNERDEAD);
SIG_DECLTYPE(SIGNAL_EPERM);
SIG_DECLTYPE(SIGNAL_EPFNOSUPPORT);
SIG_DECLTYPE(SIGNAL_EPIPE);
SIG_DECLTYPE(SIGNAL_EPROTO);
SIG_DECLTYPE(SIGNAL_EPROTONOSUPPORT);
SIG_DECLTYPE(SIGNAL_EPROTOTYPE);
SIG_DECLTYPE(SIGNAL_ERANGE);
SIG_DECLTYPE(SIGNAL_EREMCHG);
SIG_DECLTYPE(SIGNAL_EREMOTE);
SIG_DECLTYPE(SIGNAL_EREMOTEIO);
SIG_DECLTYPE(SIGNAL_ERESTART);
SIG_DECLTYPE(SIGNAL_ERFKILL);
SIG_DECLTYPE(SIGNAL_EROFS);
SIG_DECLTYPE(SIGNAL_ESHUTDOWN);
SIG_DECLTYPE(SIGNAL_ESOCKTNOSUPPORT);
SIG_DECLTYPE(SIGNAL_ESPIPE);
SIG_DECLTYPE(SIGNAL_ESRCH);
SIG_DECLTYPE(SIGNAL_ESRMNT);
SIG_DECLTYPE(SIGNAL_ESTALE);
SIG_DECLTYPE(SIGNAL_ESTRPIPE);
SIG_DECLTYPE(SIGNAL_ETIME);
SIG_DECLTYPE(SIGNAL_ETIMEDOUT);
SIG_DECLTYPE(SIGNAL_ETOOMANYREFS);
SIG_DECLTYPE(SIGNAL_ETXTBSY);
SIG_DECLTYPE(SIGNAL_EUCLEAN);
SIG_DECLTYPE(SIGNAL_EUNATCH);
SIG_DECLTYPE(SIGNAL_EUSERS);
SIG_DECLTYPE(SIGNAL_EXDEV);
SIG_DECLTYPE(SIGNAL_EXFULL);


//#define E2BIG 7
//#define EACCES 13
//#define EADDRINUSE 98
//#define EADDRNOTAVAIL 99
//#define EADV 68
//#define EAFNOSUPPORT 97
//#define EAGAIN 11
//#define EALREADY 114
//#define EBADE 52
//#define EBADF 9
//#define EBADFD 77
//#define EBADMSG 74
//#define EBADR 53
//#define EBADRQC 56
//#define EBADSLT 57
//#define EBFONT 59
//#define EBUSY 16
//#define ECANCELED 125
//#define ECHILD 10
//#define ECHRNG 44
//#define ECOMM 70
//#define ECONNABORTED 103
//#define ECONNREFUSED 111
//#define ECONNRESET 104
//#define EDEADLK 35
//#define EDEADLOCK EDEADLK
//#define EDESTADDRREQ 89
//#define EDOM 33
//#define EDOTDOT 73
//#define EDQUOT 122
//#define EEXIST 17
//#define EFAULT 14
//#define EFBIG 27
//#define EHOSTDOWN 112
//#define EHOSTUNREACH 113
//#define EHWPOISON 133
//#define EIDRM 43
//#define EILSEQ 84
//#define EINPROGRESS 115
//#define EINTR 4
//#define EINVAL 22
//#define EIO 5
//#define EISCONN 106
//#define EISDIR 21
//#define EISNAM 120
//#define EKEYEXPIRED 127
//#define EKEYREJECTED 129
//#define EKEYREVOKED 128
//#define EL2HLT 51
//#define EL2NSYNC 45
//#define EL3HLT 46
//#define EL3RST 47
//#define ELIBACC 79
//#define ELIBBAD 80
//#define ELIBEXEC 83
//#define ELIBMAX 82
//#define ELIBSCN 81
//#define ELNRNG 48
//#define ELOOP 40
//#define EMEDIUMTYPE 124
//#define EMFILE 24
//#define EMLINK 31
//#define EMSGSIZE 90
//#define EMULTIHOP 72
//#define ENAMETOOLONG 36
//#define ENAVAIL 119
//#define ENETDOWN 100
//#define ENETRESET 102
//#define ENETUNREACH 101
//#define ENFILE 23
//#define ENOANO 55
//#define ENOBUFS 105
//#define ENOCSI 50
//#define ENODATA 61
//#define ENODEV 19
//#define ENOENT 2
//#define ENOEXEC 8
//#define ENOKEY 126
//#define ENOLCK 37
//#define ENOLINK 67
//#define ENOMEDIUM 123
//#define ENOMEM 12
//#define ENOMSG 42
//#define ENONET 64
//#define ENOPKG 65
//#define ENOPROTOOPT 92
//#define ENOSPC 28
//#define ENOSR 63
//#define ENOSTR 60
//#define ENOSYS 38
//#define ENOTBLK 15
//#define ENOTCONN 107
//#define ENOTDIR 20
//#define ENOTEMPTY 39
//#define ENOTNAM 118
//#define ENOTRECOVERABLE 131
//#define ENOTSOCK 88
//#define ENOTSUP EOPNOTSUPP
//#define ENOTTY 25
//#define ENOTUNIQ 76
//#define ENXIO 6
//#define EOF (-1)
//#define EOPNOTSUPP 95
//#define EOVERFLOW 75
//#define EOWNERDEAD 130
//#define EPERM 1
//#define EPFNOSUPPORT 96
//#define EPIPE 32
//#define EPROTO 71
//#define EPROTONOSUPPORT 93
//#define EPROTOTYPE 91
//#define ERANGE 34
//#define EREMCHG 78
//#define EREMOTE 66
//#define EREMOTEIO 121
//#define ERESTART 85
//#define ERFKILL 132
//#define EROFS 30
//#define ESHUTDOWN 108
//#define ESOCKTNOSUPPORT 94
//#define ESPIPE 29
//#define ESRCH 3
//#define ESRMNT 69
//#define ESTALE 116
//#define ESTRPIPE 86
//#define ETIME 62
//#define ETIMEDOUT 110
//#define ETOOMANYREFS 109
//#define ETXTBSY 26
//#define EUCLEAN 117
//#define EUNATCH 49
//#define EUSERS 87
//#define EWOULDBLOCK EAGAIN
//#define EXDEV 18
//#define EXFULL 54


#ifdef __cplusplus
}
#endif
